export const jacketArray = [
    {
        name: "Avalanche",
        id: 1,
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sapiente architecto atque illum odit, eos ipsa! Cum, exercitationem! Voluptate culpa omnis corrupti dolore similique? Magni ab voluptatibus accusamus enim repudiandae. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nam autem error velit quas dolore esse dolorem iusto, et delectus exercitationem tenetur numquam odio fugit eaque dolor laboriosam mollitia ratione. Iure. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Assumenda natus facere accusantium unde, facilis exercitationem recusandae incidunt a adipisci iusto dicta ipsum ea modi, explicabo, id alias atque? Tempore, similique.",
        price: 39,
        color: "blue",
        imgsrc : "/New shortcut.lnk/images/products/avalanche_blue.jpg",
    },
    {
        name: "Avalanche",
        id: 2,
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sapiente architecto atque illum odit, eos ipsa! Cum, exercitationem! Voluptate culpa omnis corrupti dolore similique? Magni ab voluptatibus accusamus enim repudiandae. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nam autem error velit quas dolore esse dolorem iusto, et delectus exercitationem tenetur numquam odio fugit eaque dolor laboriosam mollitia ratione. Iure. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Assumenda natus facere accusantium unde, facilis exercitationem recusandae incidunt a adipisci iusto dicta ipsum ea modi, explicabo, id alias atque? Tempore, similique.",
        price: 39,
        color: "yellow",
        imgsrc : "/New shortcut.lnk/images/products/avalanche_yellow.jpg",
    },
    {
        name: "Avalanche",
        id: 3,
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sapiente architecto atque illum odit, eos ipsa! Cum, exercitationem! Voluptate culpa omnis corrupti dolore similique? Magni ab voluptatibus accusamus enim repudiandae. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nam autem error velit quas dolore esse dolorem iusto, et delectus exercitationem tenetur numquam odio fugit eaque dolor laboriosam mollitia ratione. Iure. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Assumenda natus facere accusantium unde, facilis exercitationem recusandae incidunt a adipisci iusto dicta ipsum ea modi, explicabo, id alias atque? Tempore, similique.",
        price: 39,
        color: "orange",
        imgsrc : "/New shortcut.lnk/images/products/avalanche_orange.jpg",
    },
    {
        name: "Mt Peak",
        id: 4,
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sapiente architecto atque illum odit, eos ipsa! Cum, exercitationem! Voluptate culpa omnis corrupti dolore similique? Magni ab voluptatibus accusamus enim repudiandae. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nam autem error velit quas dolore esse dolorem iusto, et delectus exercitationem tenetur numquam odio fugit eaque dolor laboriosam mollitia ratione. Iure. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Assumenda natus facere accusantium unde, facilis exercitationem recusandae incidunt a adipisci iusto dicta ipsum ea modi, explicabo, id alias atque? Tempore, similique.",
        price: 49,
        color: "turquoise",
        imgsrc : "/New shortcut.lnk/images/products/mt_peak_turquoise.jpg",
    },
    {
        name: "Mt Peak",
        id: 5,
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sapiente architecto atque illum odit, eos ipsa! Cum, exercitationem! Voluptate culpa omnis corrupti dolore similique? Magni ab voluptatibus accusamus enim repudiandae. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nam autem error velit quas dolore esse dolorem iusto, et delectus exercitationem tenetur numquam odio fugit eaque dolor laboriosam mollitia ratione. Iure. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Assumenda natus facere accusantium unde, facilis exercitationem recusandae incidunt a adipisci iusto dicta ipsum ea modi, explicabo, id alias atque? Tempore, similique.",
        price: 49,
        color: "yellow",
        imgsrc: "/New shortcut.lnk/images/products/mt_peak_yellow.jpg",
    },
    {
        name: "Mt Peak",
        id: 6,
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sapiente architecto atque illum odit, eos ipsa! Cum, exercitationem! Voluptate culpa omnis corrupti dolore similique? Magni ab voluptatibus accusamus enim repudiandae. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nam autem error velit quas dolore esse dolorem iusto, et delectus exercitationem tenetur numquam odio fugit eaque dolor laboriosam mollitia ratione. Iure. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Assumenda natus facere accusantium unde, facilis exercitationem recusandae incidunt a adipisci iusto dicta ipsum ea modi, explicabo, id alias atque? Tempore, similique.",
        price: 49,
        color: "pink",
        imgsrc : "/New shortcut.lnk/images/products/mt_peak_pink.jpg",
    },
    {
        name: "Snowday",
        id: 7,
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sapiente architecto atque illum odit, eos ipsa! Cum, exercitationem! Voluptate culpa omnis corrupti dolore similique? Magni ab voluptatibus accusamus enim repudiandae. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nam autem error velit quas dolore esse dolorem iusto, et delectus exercitationem tenetur numquam odio fugit eaque dolor laboriosam mollitia ratione. Iure. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Assumenda natus facere accusantium unde, facilis exercitationem recusandae incidunt a adipisci iusto dicta ipsum ea modi, explicabo, id alias atque? Tempore, similique.",
        price: 59,
        color: "green",
        imgsrc : "/New shortcut.lnk/images/products/snowday_green.jpg",
    },
    {
        name: "Snowday",
        id: 8,
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sapiente architecto atque illum odit, eos ipsa! Cum, exercitationem! Voluptate culpa omnis corrupti dolore similique? Magni ab voluptatibus accusamus enim repudiandae. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nam autem error velit quas dolore esse dolorem iusto, et delectus exercitationem tenetur numquam odio fugit eaque dolor laboriosam mollitia ratione. Iure. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Assumenda natus facere accusantium unde, facilis exercitationem recusandae incidunt a adipisci iusto dicta ipsum ea modi, explicabo, id alias atque? Tempore, similique.",
        price: 59,
        color: "blue",
        imgsrc : "/New shortcut.lnk/images/products/snowday_blue.jpg",
    },
    {
        name: "Snowday",
        id: 9,
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sapiente architecto atque illum odit, eos ipsa! Cum, exercitationem! Voluptate culpa omnis corrupti dolore similique? Magni ab voluptatibus accusamus enim repudiandae. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nam autem error velit quas dolore esse dolorem iusto, et delectus exercitationem tenetur numquam odio fugit eaque dolor laboriosam mollitia ratione. Iure. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Assumenda natus facere accusantium unde, facilis exercitationem recusandae incidunt a adipisci iusto dicta ipsum ea modi, explicabo, id alias atque? Tempore, similique.",
        price: 59,
        color: "red",
        imgsrc : "/New shortcut.lnk/images/products/snowday_red.jpg",
    },
    {
        name: "Avalanche",
        id: 10,
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sapiente architecto atque illum odit, eos ipsa! Cum, exercitationem! Voluptate culpa omnis corrupti dolore similique? Magni ab voluptatibus accusamus enim repudiandae. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nam autem error velit quas dolore esse dolorem iusto, et delectus exercitationem tenetur numquam odio fugit eaque dolor laboriosam mollitia ratione. Iure. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Assumenda natus facere accusantium unde, facilis exercitationem recusandae incidunt a adipisci iusto dicta ipsum ea modi, explicabo, id alias atque? Tempore, similique.",
        price: 39,
        color: "blue",
        imgsrc : "/New shortcut.lnk/images/products/avalanche_blue.jpg",
    },
    {
        name: "Avalanche",
        id: 11,
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sapiente architecto atque illum odit, eos ipsa! Cum, exercitationem! Voluptate culpa omnis corrupti dolore similique? Magni ab voluptatibus accusamus enim repudiandae. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nam autem error velit quas dolore esse dolorem iusto, et delectus exercitationem tenetur numquam odio fugit eaque dolor laboriosam mollitia ratione. Iure. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Assumenda natus facere accusantium unde, facilis exercitationem recusandae incidunt a adipisci iusto dicta ipsum ea modi, explicabo, id alias atque? Tempore, similique.",
        price: 39,
        color: "yellow",
        imgsrc : "/New shortcut.lnk/images/products/avalanche_yellow.jpg",
    },
    {
        name: "Avalanche",
        id: 12,
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sapiente architecto atque illum odit, eos ipsa! Cum, exercitationem! Voluptate culpa omnis corrupti dolore similique? Magni ab voluptatibus accusamus enim repudiandae. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nam autem error velit quas dolore esse dolorem iusto, et delectus exercitationem tenetur numquam odio fugit eaque dolor laboriosam mollitia ratione. Iure. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Assumenda natus facere accusantium unde, facilis exercitationem recusandae incidunt a adipisci iusto dicta ipsum ea modi, explicabo, id alias atque? Tempore, similique.",
        price: 39,
        color: "orange",
        imgsrc : "/New shortcut.lnk/images/products/avalanche_orange.jpg",
    },
    {
        name: "Mt Peak",
        id: 13,
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sapiente architecto atque illum odit, eos ipsa! Cum, exercitationem! Voluptate culpa omnis corrupti dolore similique? Magni ab voluptatibus accusamus enim repudiandae. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nam autem error velit quas dolore esse dolorem iusto, et delectus exercitationem tenetur numquam odio fugit eaque dolor laboriosam mollitia ratione. Iure. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Assumenda natus facere accusantium unde, facilis exercitationem recusandae incidunt a adipisci iusto dicta ipsum ea modi, explicabo, id alias atque? Tempore, similique.",
        price: 49,
        color: "turquoise",
        imgsrc : "/New shortcut.lnk/images/products/mt_peak_turquoise.jpg",
    },
    {
        name: "Mt Peak",
        id: 14,
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sapiente architecto atque illum odit, eos ipsa! Cum, exercitationem! Voluptate culpa omnis corrupti dolore similique? Magni ab voluptatibus accusamus enim repudiandae. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nam autem error velit quas dolore esse dolorem iusto, et delectus exercitationem tenetur numquam odio fugit eaque dolor laboriosam mollitia ratione. Iure. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Assumenda natus facere accusantium unde, facilis exercitationem recusandae incidunt a adipisci iusto dicta ipsum ea modi, explicabo, id alias atque? Tempore, similique.",
        price: 49,
        color: "yellow",
        imgsrc: "/New shortcut.lnk/images/products/mt_peak_yellow.jpg",
    },
    {
        name: "Mt Peak",
        id: 15,
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sapiente architecto atque illum odit, eos ipsa! Cum, exercitationem! Voluptate culpa omnis corrupti dolore similique? Magni ab voluptatibus accusamus enim repudiandae. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nam autem error velit quas dolore esse dolorem iusto, et delectus exercitationem tenetur numquam odio fugit eaque dolor laboriosam mollitia ratione. Iure. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Assumenda natus facere accusantium unde, facilis exercitationem recusandae incidunt a adipisci iusto dicta ipsum ea modi, explicabo, id alias atque? Tempore, similique.",
        price: 49,
        color: "pink",
        imgsrc : "/New shortcut.lnk/images/products/mt_peak_pink.jpg",
    },
    {
        name: "Snowday",
        id: 16,
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sapiente architecto atque illum odit, eos ipsa! Cum, exercitationem! Voluptate culpa omnis corrupti dolore similique? Magni ab voluptatibus accusamus enim repudiandae. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nam autem error velit quas dolore esse dolorem iusto, et delectus exercitationem tenetur numquam odio fugit eaque dolor laboriosam mollitia ratione. Iure. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Assumenda natus facere accusantium unde, facilis exercitationem recusandae incidunt a adipisci iusto dicta ipsum ea modi, explicabo, id alias atque? Tempore, similique.",
        price: 59,
        color: "green",
        imgsrc : "/New shortcut.lnk/images/products/snowday_green.jpg",
    },
    {
        name: "Snowday",
        id: 17,
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sapiente architecto atque illum odit, eos ipsa! Cum, exercitationem! Voluptate culpa omnis corrupti dolore similique? Magni ab voluptatibus accusamus enim repudiandae. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nam autem error velit quas dolore esse dolorem iusto, et delectus exercitationem tenetur numquam odio fugit eaque dolor laboriosam mollitia ratione. Iure. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Assumenda natus facere accusantium unde, facilis exercitationem recusandae incidunt a adipisci iusto dicta ipsum ea modi, explicabo, id alias atque? Tempore, similique.",
        price: 59,
        color: "blue",
        imgsrc : "/New shortcut.lnk/images/products/snowday_blue.jpg",
    },
    {
        name: "Snowday",
        id: 18,
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sapiente architecto atque illum odit, eos ipsa! Cum, exercitationem! Voluptate culpa omnis corrupti dolore similique? Magni ab voluptatibus accusamus enim repudiandae. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nam autem error velit quas dolore esse dolorem iusto, et delectus exercitationem tenetur numquam odio fugit eaque dolor laboriosam mollitia ratione. Iure. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Assumenda natus facere accusantium unde, facilis exercitationem recusandae incidunt a adipisci iusto dicta ipsum ea modi, explicabo, id alias atque? Tempore, similique.",
        price: 59,
        color: "red",
        imgsrc : "/New shortcut.lnk/images/products/snowday_red.jpg",
    },
];